<h1>Create<p></h1>
<?php

$form = $this->form;
$form->prepare();


// Assuming the "contact/process" route exists...
$form->setAttribute('action', $this->url('registro/index/create'));

// Set the method attribute for the form
$form->setAttribute('method', 'post');

// Get the form label plugin
$formLabel = $this->plugin('formLabel');

// Render the opening tag
echo $this->form()->openTag($form);

 
?>

